# Use the official Node.js base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app/SQSConsumer

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci
# RUN npm install

# Copy the rest of the application code
COPY . .

# Build TypeScript files
RUN npm run build

# Start the application
# CMD npm start
CMD npm run dev