version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: point
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Seoul

    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
