version: '3.9'

services:
  point-service:
    container_name: point-service
    build:
      context: ./PointService
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./env/.env
    depends_on:
      - db
    restart: always
    volumes:
      # - ./src:/app/src
      - ./PointService/src:/app/PointService/src
  sqs-consumer:
    container_name: sqs-consumer
    build:
      context: ./SQSConsumer
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./env/.env
    depends_on:
      - db
    restart: always
    volumes:
      - ./SQSConsumer/src:/app/SQSConsumer/src

  # db:
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - 3307:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: point
  #     MYSQL_USER: test
  #     MYSQL_PASSWORD: test
  #     TZ: Asia/Seoul

  #   volumes:
  #     - db_data:/var/lib/mysql

  db:
    container_name: db
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=28828bb8ec779fc98b63a323bcb644f49023af728bc84f7800f4e9
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TIMEZONE=Asia/Seoul
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
